name: geoschool
description: GeoSchool mobile app
publish_to: "none"
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI & archi
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  # Réseau / util
  dio: ^5.6.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  intl: ^0.19.0
  # Carte
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  shared_preferences: ^2.3.2
  # Push (optionnel mais prêt)
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
